platform :ios, ‘9.1’
source 'https://github.com/CocoaPods/Specs.git'

target ‘kiboLiveChat’ do
use_frameworks!
pod 'Alamofire', '~> 3.0'
pod ’SwiftyJSON’
pod "SQLite.swift",
git: "https://github.com/stephencelis/SQLite.swift",
  branch: "cocoapods-xcode-7-3"
end
