platform :ios, ‘9.1’
source 'https://github.com/CocoaPods/Specs.git'

target ‘KiboEngageSDK’ do
pod 'EPContactsPicker'
use_frameworks!

pod 'Alamofire', '~> 3.0'
pod 'SQLite.swift', '~> 0.10.1'
pod ‘SwiftyJSON’
end
